FROM docker:20.10.22-dind-alpine3.17

RUN apk update && apk --no-cache --update add \
    py3-pip \
    python3 \
    make \
    bash \
    git \
    curl \
    lksctp-tools \
    ca-certificates \
    erlang

RUN curl -s -L \
    -o /usr/local/bin/rebar3 \
    https://github.com/erlang/rebar3/releases/download/3.20.0/rebar3 && \
    chmod +x /usr/local/bin/rebar3
